/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50506
Source Host           : localhost:3306
Source Database       : xingtu

Target Server Type    : MYSQL
Target Server Version : 50506
File Encoding         : 65001

Date: 2018-12-15 20:59:07
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `youjidiv`
-- ----------------------------
DROP TABLE IF EXISTS `youjidiv`;
CREATE TABLE `youjidiv` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `context` text CHARACTER SET utf8,
  `sid` int(11) NOT NULL,
  `address` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of youjidiv
-- ----------------------------
INSERT INTO `youjidiv` VALUES ('2', '市博 九天开出一成都', '<p class=\"first\" style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	&emsp;&emsp;是这个时代变化太快，还是我们固守着自己的世界不愿意去改变？\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	&emsp;&emsp;我想，那些坚持怀旧的人，大概在那个曾经熟悉的世界里，总有些不愿意失去，却早已不能再拥有的过去，就像埋在心底的初恋，也像早已化作一帧帧黑白照片模样的童年。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/d46175033610a09fd9846f0ee2f00347.jpg_r_680x237x95_45176359.jpg\" alt=\"\" />\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;面对历史长河的时候，我觉得自己连一粒沙都不是。\r\n	</p>\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;沙不管如何总会随着江水奔流入海，而自己却短暂得像滚滚江水前进时偶尔泛起的一圈涟漪，或许会一环一环激发那些后续的波浪，到底却画了一个圆以后，便消失不见。\r\n	</p>\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;所以，我觉得我的第一站应该前往市博，因为爱她，便要先了解她；而要学会敬畏，就该用解读历史的方式去仰视她。\r\n	</p>\r\n<img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/ac3f3ac0e940ec74eafb9b1c195659fb.jpg_r_680x237x95_275975ef.jpg\" alt=\"\" />\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;我是不大逛博物馆的，不是因为不喜欢，而是因为每次去总会在里面耗上太多时间，每一件哪怕看起来极小的展品，都饱含了千年的历史，然后被几行简单的介绍给概括了大众，即便如此，想要看完所有的展品，那也是极其需要定力的一件事。\r\n	</p>\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;这个时代，这个年岁的我，太浮躁，又太渴求，于是总觉得逛博物馆有些力不从心。\r\n	</p>\r\n<img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/3e003a11ed1165db51f7754dbe969cd3.jpg_r_453x680x95_301ffee8.jpg\" alt=\"\" />\r\n</p>', '2', '成都博物馆');
INSERT INTO `youjidiv` VALUES ('3', '宽窄巷子 浅色寂寞', '<p class=\"first\" style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	&emsp;灯火阑珊处，其实最容易寂寞。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	&emsp;&emsp;因为那些人间明明灭灭的光，总是把形单影只的影子照得无所遁形。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/6e5cefcdf33cd49408c9e3f4e5633cf1.jpg_r_680x237x95_9132ee07.jpg\" alt=\"\" />\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">&emsp;&emsp;</span><a href=\"http://travel.qunar.com/p-oi701768-kuanzhaixiangzi\" target=\"_blank\" class=\"link_dest\">宽窄巷子</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">其实有三条巷子，宽一点的叫宽巷子，窄一点的叫窄巷子，有井的就叫</span><a href=\"http://travel.qunar.com/p-oi8454531-jingxiangzi\" target=\"_blank\" class=\"link_dest\">井巷子</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">。曾经满清南下的满城与土著的少城融合后，诞生了这一片潜藏时光的所在，巷子的名字不过来自于民国时期很是随意的勘测。</span>\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/7a43070236f023b5776f051874d60192.jpg_r_680x453x95_581dfb93.jpg\" alt=\"\" />\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;而今时今日，藏于市中心万千繁华深处的这几条老巷子，倒更像是游客如织的热门景点。\r\n	</p>\r\n	<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n		&emsp;&emsp;走在宽窄里，总有种身在<a href=\"http://travel.qunar.com/p-cs300085-chengdu\" target=\"_blank\" class=\"link_dest\">成都</a>却又并未在<a href=\"http://travel.qunar.com/p-cs300085-chengdu\" target=\"_blank\" class=\"link_dest\">成都</a>的错觉，那是因为这里有着最<a href=\"http://travel.qunar.com/p-cs300085-chengdu\" target=\"_blank\" class=\"link_dest\">成都</a>本土的气质，但是听到的呢喃交谈却鲜有<a href=\"http://travel.qunar.com/p-cs300085-chengdu\" target=\"_blank\" class=\"link_dest\">成都</a>话，来自祖国各地的南腔北调总是满满充斥耳畔。\r\n	</p>\r\n<img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/e8dfa6c10f91ac10c49528ee05321f96.jpg_r_680x453x95_92e40c8b.jpg\" alt=\"\" />\r\n</p>', '2', '宽窄巷子');
INSERT INTO `youjidiv` VALUES ('4', '初雪来后的第一轮火锅', '<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">&emsp;&emsp;走进这家店原本是个意外，走在</span><a href=\"http://travel.qunar.com/p-oi7568504-paotongshujie\" target=\"_blank\" class=\"link_dest\">泡桐树街</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">头的时候突然听到有人招呼我，我转头四下张望，虽然并不算太晚，或许是大降温的缘故，今日</span><a href=\"http://travel.qunar.com/p-cs300085-chengdu\" target=\"_blank\" class=\"link_dest\">成都</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">的街头的我竟显得如此的形只影单。</span>\r\n</p>\r\n<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\"><img src=\"https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/c93d7b593b71b2cc2b1b0d005d885935.jpg_r_680x237x95_af1a17b3.jpg\" alt=\"\" /><br />\r\n</span>\r\n</p>', '2', '牛灯影私房老火锅');
INSERT INTO `youjidiv` VALUES ('5', '文青最爱，艺术家聚集地', '<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">酒厂·ART国际艺术园是由经营不善的酒厂重新改造而成，紧邻</span><a href=\"http://travel.qunar.com/p-oi8605642-zhongyangmeishuxueyuan\" target=\"_blank\" class=\"link_dest\">中央美术学院</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">，处在望京自由艺术家、艺术机构集散中心</span><img src=\"https://img1.qunarzz.com/travel/d1/1809/b4/4943292f577215b5.jpg\" alt=\"\" />\r\n</p>\r\n<p>\r\n	<img src=\"https://img1.qunarzz.com/travel/d8/1809/c2/264d951dab3673b5.jpg\" alt=\"\" />\r\n</p>', '3', '酒厂国际艺术园');
INSERT INTO `youjidiv` VALUES ('6', '一股文艺的气息扑面而来~~', '<a href=\"http://travel.qunar.com/p-oi10006225-fangjiahutong\" target=\"_blank\" class=\"link_dest\">方家胡同</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">里最值得一提的就是46号院，号称“市内798”。这里是过去的中国机床厂厂址，是</span><a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">工业史上重要的“机床基地”，植根于丰厚文化积淀的沃土中，形成了独特的现代文化与市井生活的对话景观，是一个以空间艺术与视觉艺术为主体的创意园区，里面还有一些文化创意公司。</span><img src=\"https://img1.qunarzz.com/travel/d6/1809/34/8014f4da3b7b31b5.jpg_r_680x451x95_3713e20b.jpg\" alt=\"\" />', '3', '方家胡同46号');
INSERT INTO `youjidiv` VALUES ('7', '无人不知798', '<p class=\"first\" style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>作为古都，不仅有愈多的历史文化遗产，历史古迹，也有着许多现代化的流行文化和艺术，是国内文艺青年聚集的城市。<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>各大<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>，又是这个城市最具艺术气息的区域。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	相信大家都知道<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>的<a href=\"http://travel.qunar.com/p-oi722952-798yishuqu\" target=\"_blank\" class=\"link_dest\">798艺术区</a>，但<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>可不是只有798哦，<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>这五个<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>都有很强的文艺范，没空出去旅行？来这些<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>放松下心情吧！\r\n</p>\r\n<img src=\"http://pic7.nipic.com/20100511/4742084_132507038603_2.jpg\" alt=\"\" />', '3', '798艺术区');
INSERT INTO `youjidiv` VALUES ('8', '文青最爱，艺术家聚集地', '<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">酒厂·ART国际艺术园是由经营不善的酒厂重新改造而成，紧邻</span><a href=\"http://travel.qunar.com/p-oi8605642-zhongyangmeishuxueyuan\" target=\"_blank\" class=\"link_dest\">中央美术学院</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">，处在望京自由艺术家、艺术机构集散中心</span><img src=\"https://img1.qunarzz.com/travel/d1/1809/b4/4943292f577215b5.jpg\" alt=\"\" />\r\n</p>\r\n<p>\r\n	<img src=\"https://img1.qunarzz.com/travel/d8/1809/c2/264d951dab3673b5.jpg\" alt=\"\" />\r\n</p>', '4', '酒厂国际艺术园');
INSERT INTO `youjidiv` VALUES ('9', '一股文艺的气息扑面而来~~', '<a href=\"http://travel.qunar.com/p-oi10006225-fangjiahutong\" target=\"_blank\" class=\"link_dest\">方家胡同</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">里最值得一提的就是46号院，号称“市内798”。这里是过去的中国机床厂厂址，是</span><a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">工业史上重要的“机床基地”，植根于丰厚文化积淀的沃土中，形成了独特的现代文化与市井生活的对话景观，是一个以空间艺术与视觉艺术为主体的创意园区，里面还有一些文化创意公司。</span><img src=\"https://img1.qunarzz.com/travel/d6/1809/34/8014f4da3b7b31b5.jpg_r_680x451x95_3713e20b.jpg\" alt=\"\" />', '4', '方家胡同46号');
INSERT INTO `youjidiv` VALUES ('10', '无人不知798', '<p class=\"first\" style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>作为古都，不仅有愈多的历史文化遗产，历史古迹，也有着许多现代化的流行文化和艺术，是国内文艺青年聚集的城市。<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>各大<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>，又是这个城市最具艺术气息的区域。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	相信大家都知道<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>的<a href=\"http://travel.qunar.com/p-oi722952-798yishuqu\" target=\"_blank\" class=\"link_dest\">798艺术区</a>，但<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>可不是只有798哦，<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>这五个<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>都有很强的文艺范，没空出去旅行？来这些<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>放松下心情吧！\r\n</p>\r\n<img src=\"http://pic7.nipic.com/20100511/4742084_132507038603_2.jpg\" alt=\"\" />', '4', '798艺术区');
INSERT INTO `youjidiv` VALUES ('11', '文青最爱，艺术家聚集地', '<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">酒厂·ART国际艺术园是由经营不善的酒厂重新改造而成，紧邻</span><a href=\"http://travel.qunar.com/p-oi8605642-zhongyangmeishuxueyuan\" target=\"_blank\" class=\"link_dest\">中央美术学院</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">，处在望京自由艺术家、艺术机构集散中心</span><img src=\"https://img1.qunarzz.com/travel/d1/1809/b4/4943292f577215b5.jpg\" alt=\"\" />\r\n</p>\r\n<p>\r\n	<img src=\"https://img1.qunarzz.com/travel/d8/1809/c2/264d951dab3673b5.jpg\" alt=\"\" />\r\n</p>', '5', '酒厂国际艺术园');
INSERT INTO `youjidiv` VALUES ('12', '一股文艺的气息扑面而来~~', '<a href=\"http://travel.qunar.com/p-oi10006225-fangjiahutong\" target=\"_blank\" class=\"link_dest\">方家胡同</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">里最值得一提的就是46号院，号称“市内798”。这里是过去的中国机床厂厂址，是</span><a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">工业史上重要的“机床基地”，植根于丰厚文化积淀的沃土中，形成了独特的现代文化与市井生活的对话景观，是一个以空间艺术与视觉艺术为主体的创意园区，里面还有一些文化创意公司。</span><img src=\"https://img1.qunarzz.com/travel/d6/1809/34/8014f4da3b7b31b5.jpg_r_680x451x95_3713e20b.jpg\" alt=\"\" />', '5', '方家胡同46号');
INSERT INTO `youjidiv` VALUES ('13', '无人不知798', '<p class=\"first\" style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>作为古都，不仅有愈多的历史文化遗产，历史古迹，也有着许多现代化的流行文化和艺术，是国内文艺青年聚集的城市。<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>各大<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>，又是这个城市最具艺术气息的区域。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	相信大家都知道<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>的<a href=\"http://travel.qunar.com/p-oi722952-798yishuqu\" target=\"_blank\" class=\"link_dest\">798艺术区</a>，但<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>可不是只有798哦，<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a>这五个<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>都有很强的文艺范，没空出去旅行？来这些<a href=\"http://travel.qunar.com/p-oi10077283-yishujiequ\" target=\"_blank\" class=\"link_dest\">艺术街区</a>放松下心情吧！\r\n</p>\r\n<img src=\"http://pic7.nipic.com/20100511/4742084_132507038603_2.jpg\" alt=\"\" />', '5', '798艺术区');
INSERT INTO `youjidiv` VALUES ('14', '落叶纷飞，物是人非', '<p class=\"first\" style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<a href=\"http://travel.qunar.com/p-cs299914-beijing\" target=\"_blank\" class=\"link_dest\">北京</a><a href=\"http://travel.qunar.com/p-oi703209-zhongshangongyuan\" target=\"_blank\" class=\"link_dest\">中山公园</a>以明清皇帝用来祭祀的“<a href=\"http://travel.qunar.com/p-oi7644772-shejitan\" target=\"_blank\" class=\"link_dest\">社稷坛</a>”为中心，除了参观历史建筑，了解古代祭祀文化，园内还有不少绿植花卉。每年春天，月季、郁金香等鲜花盛放，秋季还有金黄的银杏叶，是市内悠闲漫步、摄影观光的好去处。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	每到秋季时，园内的一小片银杏林树叶金黄，也是摄影的不错选择。\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<img src=\"https://img1.qunarzz.com/travel/d9/1810/ef/bd46e6a86bd1f5b5.jpg_r_680x453x95_3997158b.jpg\" alt=\"\" />\r\n</p>\r\n<p style=\"font-size:14px;color:#333333;font-family:arial, tahoma, sans-serif;background-color:#FFFFFF;\">\r\n	<img src=\"https://img1.qunarzz.com/travel/d0/1810/72/0c975342cc0aabb5.jpg_r_680x453x95_4a48e5a6.jpg\" alt=\"\" />\r\n</p>', '6', '中山公园');
INSERT INTO `youjidiv` VALUES ('15', '人山人海，只为你回眸', '<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">“让我们荡起双桨，小船儿推开波浪…”，耳熟能详的歌中描述的正是这里。北海位于</span><a href=\"http://travel.qunar.com/p-oi710603-gugong\" target=\"_blank\" class=\"link_dest\">故宫</a><span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\">西北侧，与“中海”“南海”合称三海。公园曾是皇家园林，园内亭台错落掩映，湖畔林木郁郁葱葱，风光极美。</span>\r\n</p>\r\n<p>\r\n	<span style=\"color:#333333;font-family:arial, tahoma, sans-serif;font-size:14px;background-color:#FFFFFF;\"><img src=\"https://img1.qunarzz.com/travel/d3/1810/f7/fa88eb0379eb49b5.jpg_r_680x452x95_1cf4ab20.jpg\" alt=\"\" /><br />\r\n</span>\r\n</p>', '6', '北海公园');
